#!/bin/sh
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".


if [ -f .lastver ]; then
    VER=$(cat .lastver)
    grep -qs "^$VER" "$1" || echo "$VER" >> "$1"
    rm .lastver
fi    
SUB=$(git submodule)
grep -qs "^$SUB" "$1" || echo "$SUB" >> "$1"
SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"