#!/bin/bash
# tag uz je prirazeny, neni co delat
if [ -n "$(git tag --contains HEAD)" ]; then
  exit 0
fi

# zjistime editor
editor=${EDITOR:-$(git config --get core.editor)}
if [ -z "${editor}" ]; then
  echo "error: editor is not set"
  exit 1
fi

# precteme jmeno projektu
url=$(git config --get remote.origin.url)
name=$(basename ${url})
if [ -z "${name}" ]; then
  echo "error: remote url not found"
  exit 1
fi

# zjistime aktualni branch
branch=$(git branch --show-current)
if [ -z "${branch}" ]; then
  echo "error: branch is not defined"
  exit 1
fi

# akci provadime pouze pro master/main branch
if [ "${branch:0:6}" == "master" ] || [ "${branch:0:4}" == "main" ]; then
  while true; do
    # pozadame o zadani verze/tagu
    tmpfile=$(mktemp)
    echo -en "$(git describe --tags --abbrev=0)" > ${tmpfile}
    ${editor} < /dev/tty ${tmpfile}
    version=$(tail -n1 ${tmpfile})
    rm ${tmpfile}

    # zkontrolujeme validitu verze/tagu
    if [ -n "$(echo ${version} | egrep -x '[0-9]+\.[0-9]+\.[0-9]+\.0')" ]; then
      echo "error: development version number"
    elif [ -z "$(echo ${version} | egrep -x '[0-9]+\.[0-9]+\.[0-9]+')" ] && [ -z "$(echo ${version} | egrep -x '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')" ]; then
      echo "error: wrong version number"
    # zkontrolujeme unikatnost verze/tagu
    elif [ -n "$(git tag --list | fgrep -x ${version})" ]; then
      echo "error: already used version number"
    else
      break
    fi
  done

  # vytvorime anotovany tag
  tmpfile=$(mktemp)
  echo "${name} ${version}" > ${tmpfile}
  git submodule >> ${tmpfile}
  git tag -F ${tmpfile} -a "${version}"
fi

