#!/bin/bash
# zjistime aktualni branch
branch=$(git branch --show-current)
if [ -z "${branch}" ]; then
  echo "error: branch is not defined"
  exit 1
fi

# akci provadime pouze pro master/main branch
if [ "${branch:0:6}" == "master" ] || [ "${branch:0:4}" == "main" ]; then
  # a pouze pri merge z jine branch
  reflog=$(git reflog -1 | cut -d: -f2)
  if [ -z "$(echo $reflog | grep 'origin/master')" ] && [ -z "$(echo $reflog | grep 'origin/main')" ]; then
    # zjistime, kde hledat cislo verze
    version_file=$(grep version_file info.txt  | cut -d: -f 2)
    version_string=$(grep version_string info.txt  | cut -d: -f 2)
    version=$(git describe | cut -d'-' -f 1 | cut -d. -f 1,2,3)

    # zmenime cislo verze na vyvojovou
    if [ -n "${version_file}" ]; then
      sed -i "s/\(${version_string}\).*/\1 \"${version}.0\"/" "${version_file}"
    else
      sed -i "s/version_string:.*/version_string:${version}.0/" info.txt
    fi
  fi
fi

